title = "Regionalny Ośrodek Debaty Międzynarodowej – Łódź"
baseURL = "https://www.rodm-lodz.pl"
disableKinds = ["taxonomy", "taxonomyTerm"]
summaryLength = 40
[params]
  description = "RODM w Łodzi to część sieci informacyjnej MSZ promującej polską politykę zagraniczną. Przybliżamy mieszkańcom woj. łódzkiego politykę zagraniczną i wzmacniamy kanały współpracy pomiędzy MSZ, samorządem i NGO-sami."
  images = ["/img/feature.png"]
  cloudinary_url = "https://res.cloudinary.com/inspro/image/upload"
[blackfriday]
  fractions = false
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
